CREATE TABLE transactions(
                       id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       sourceApp VARCHAR(150) NOT NULL,
                       command VARCHAR(255) NOT NULL,
                       callbackId INT NOT NULL,
                       payload CLOB,
                       result CLOB,
                       status INT,
                       created TIMESTAMP,
                       completed TIMESTAMP,
                       PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idxCallbackId on transactions(callbackId);